const data = [
  //Rajouter clef: description 
  {
    id: 0,
    path: "/img/Assets/ShopRoom.png",
    up: false,
    down: "false",
    left: false,
    right: false,
    shop: true,
    //description: "text"
  },
  {
    id: 1,
    path: "/img/maps/map_0/Map1.png",
    up: false,
    down: false,
    left: false,
    right: "/map/2",
    shop: false,
  },
  {
    id: 2,
    path: "/img/maps/map_0/Map2.png",
    up: "/map/3",
    down: false,
    left: "/map/1",
    right: false,
    shop: false,
  },
  {
    id: 3,
    path: "/img/maps/map_0/Map3.png",
    up: false,
    down: "/map/2",
    left: false,
    right: "/map/4",
    shop: false,
  },
  {
    id: 4,
    path: "/img/maps/map_0/Map4.png",
    up: false,
    down: "/map/5",
    left: "/map/3",
    right: false,
    shop: false,
  },
  {
    id: 5,
    path: "/img/maps/map_0/Map5.png",
    up: "/map/4",
    down: "/map/6",
    left: false,
    right: false,
    shop: false,
  },
  {
    id: 6,
    path: "/img/maps/map_0/Map6.png",
    up: "/map/5",
    down: "/map/7",
    left: false,
    right: false,
    shop: true,
  },
  {
    id: 7,
    path: "/img/maps/map_0/Map7.png",
    up: "/map/6",
    down: "/map/8",
    left: false,
    right: false,
    shop: false,
  },
  {
    id: 8,
    path: "/img/maps/map_0/Map8.png",
    up: "/map/7",
    down: "/map/9",
    left: "/map/13",
    right: false,
    shop: false,
  },
  {
    id: 9,
    path: "/img/maps/map_0/Map9.png",
    up: "/map/8",
    down: "/map/12",
    left: "/map/10",
    right: "/map/11",
    shop: false,
  },
  {
    id: 10,
    path: "/img/maps/map_0/Map10.png",
    up: false,
    down: false,
    left: false,
    right: "/map/9",
    shop: false,
  },
  {
    id: 11,
    path: "/img/maps/map_0/Map11.png",
    up: false,
    down: false,
    left: "/map/9",
    right: false,
    shop: false,
  },
  {
    id: 12,
    path: "/img/maps/map_0/Map12.png",
    up: "/map/9",
    down: false,
    left: false,
    right: false,
    shop: false,
  },
  {
    id: 13,
    path: "/img/maps/map_0/Map13.png",
    up: false,
    down: false,
    left: false,
    right: "/map/8",
    shop: false,
  },
];

export default data;
