 const data = [
    {
      id: 0,
      path: "/img/Assets/ShopRoom.png",
      up: false,
      down: "false",
      left: false,
      right: false,
      shop: true,
    },
    {
      id: 1,
      path: "/img/maps/map_0/Map1.png",
      up: false,
      down: false,
      left: false,
      right: "/map/2",
      shop: false,
    },
    {
      id: 2,
      path: "/img/maps/map_0/Map2.png",
      up: "/map/3",
      down: false,
      left: "/map/1",
      right: false,
      shop: false,
    },
    {
      id: 3,
      path: "/img/maps/map_0/Map3.png",
      up: false,
      down: false,
      left: "/map/2",
      right: "/map/4",
      shop: false,
    },
    {
      id: 4,
      path: "/img/maps/map_0/Map4.png",
      up: false,
      down: "/map/5",
      left: "/map/3",
      right: false,
      shop: false,
    },
    {
      id: 5,
      path: "/img/maps/map_0/Map5.png",
      up: false,
      down: false,
      left: "/map/6",
      right: "/map/4",
      shop: false,
    },
    {
      id: 6,
      path: "/img/maps/map_0/Map6.png",
      up: "/map/5",
      down: "/map/7",
      left: false,
      right: false,
      shop: true,
    },
    {
      id: 7,
      path: "/img/maps/map_0/Map7.png",
      up: false,
      down: "/map/8",
      left: false,
      right: "/map/6",
      shop: false,
    },
    {
      id: 8,
      path: "/img/maps/map_0/Map8.png",
      up: "/map/7",
      down: false,
      left: false,
      right: false,
      shop: false,
    },
    
  ];

  export default data;